version: 2

models:
  - name: dim_committee
    description: "A table storing detailed information about contributions, including committee ID, transaction types, and amounts."
    columns:
      - name: contributionKey
        description: "The unique identifier for each contribution record."
      - name: CMTE_ID
        description: "Committee ID associated with the contribution."
      - name: AMNDT_IND
        description: "Indicator of whether the contribution is an amendment."
      - name: RPT_TP
        description: "The report type under which the contribution was made."
      - name: TRANSACTION_PGI
        description: "Indicator of whether the contribution is for primary or general election."
      - name: TRANSACTION_TP
        description: "The type of transaction."
      - name: NAME
        description: "The name of the contributor, lender, or transfer entity."
      - name: ZIP_CODE
        description: "The ZIP code of the contributor."
      - name: TRANSACTION_DT
        description: "The date when the transaction occurred."
      - name: TRANSACTION_AMT
        description: "The amount of the transaction."
      - name: OTHER_ID
        description: "An additional identification number for the transaction."
      - name: CAND_ID
        description: "The candidate ID associated with the contribution."
      - name: TRAN_ID
        description: "A unique identifier for the transaction."
      - name: MEMO_CD
        description: "A code indicating if the transaction has a memo."
      - name: MEMO_TEXT
        description: "The text of any memo associated with the transaction."
