CREATE TABLE dim_candidate (
    contributionKey INT PRIMARY KEY,
    CMTE_ID VARCHAR(255),
    AMNDT_IND VARCHAR(1),
    RPT_TP VARCHAR(10),
    TRANSACTION_PGI VARCHAR(1),
    TRANSACTION_TP VARCHAR(20),
    NAME VARCHAR(255),
    ZIP_CODE INT,
    TRANSACTION_DT DATE,
    TRANSACTION_AMT DECIMAL(18,2),
    OTHER_ID INT,
    CAND_ID INT,
    TRAN_ID VARCHAR(255),
    MEMO_CD VARCHAR(1),
    MEMO_TEXT VARCHAR(1000)
);
